spring:
  #  datasource:
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    url: jdbc:mysql://localhost:3306/payheredb?serverTimezone=Asia;
  #    username: sa
  #    password: sa
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none # JPA Setting
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
    show-sql: true
    defer-datasource-initialization: true
  sql: # SQL init
    init:
      mode: always
  h2:
    console:
      enabled: true

logging:
  level:
    org:
      hibernate:
        type: trace

security:
  jwt:
    token:
      secret-key: payhear@dPtnfwjdasdkkasjdnvxcu32ad128znczSs2n42dbashdyasdbav2Clvyx9vsnasd
      access:
        expire-length : 3600000 #1시간

cors:
  allow-origin:
    urls: http://localhost:8080, http://localhost:3000